### ISSUE TITLE
10/4/2022 10:45AM - Model Draft Discussion Round 2

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Project-1-eStreamingMovies#13]
**GOAL: Review the CS381 Project Planning Document and the Project 1 Specification.** 

**Attendance:** 
- [x] Amber Garcia
- [x] Adrian Noa
- [x] Jasminder Garcha
- [x] Wade Li
- [ ] Oliver Vidal

**To-Dos:**
- [x] Schedule time for meeting with everyone's confirmation
- [ ] Read over the positives, negatives, and suggested features for the DM
- [x] Start drafting the CDM
- [ ] Creating Definitions for relationships and the business objects

**Notes:**
- View Notes for https://github.com/G915-2-Data-Modeling-381/Project-1-eStreamingMovies/issues/8 to push to this meeting
