### ISSUE TITLE
Project Plan Specification 4-6

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Project-1-eStreamingMovies#40]
Create a description up 2 - 6 sentences long for each number assigned.
- [x] 4. List agencies, stakeholders or divisions which will be impacted by this project and describe how they will be affected by the project.
- [x] 5. List business processes or systems which will be impacted by this project and describe how they will be affected.
- [x] 6. Describe any specific components that are excluded from this project.

**Comment by adrianmnh** [comment]
Agencies impacted by the modernization of our organization are as follows:
- asda
