### ISSUE TITLE
9/30/2022 4:00PM - Model Presentation Meeting

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Project-1-eStreamingMovies#5]
**GOAL: Present each others model designs and create new version** 

**Attendance:** 
- [x] Amber Garcia
- [x] Adrian Noa
- [x] Jasminder Garcha
- [x] Wade Li
- [x] Oliver Vidal

**To-Dos:**
- [x] Each member present their model to the group in erwinDB 
- [x] Discuss the positives/negatives of each member's model
- [x] Collect data on the best features of each member's work
- [x] Incorporate thoughts into new CDM, LDM, and PDM

**Notes:**
https://github.com/G915-2-Data-Modeling-381/Project-1-eStreamingMovies/blob/main/Model_Highlights/AnalysisNotes.md

All models were presented, analyzed, and were given constructive feedback on the uniqueness and detail of their models. A full list of the information is in the available link, to be added as markdown file soon.
