### ISSUE TITLE
10/1/2022 3:00PM - Model Draft Discussion

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Project-1-eStreamingMovies#8]
**GOAL: Review the CS381 Project Planning Document and the Project 1 Specification.** 

**Attendance:** 
- [x] Amber Garcia
- [ ] Adrian Noa
- [x] Jasminder Garcha
- [x] Wade Li
- [ ] Oliver Vidal

**To-Dos:**
- [ ] Read over the positives, negatives, and suggested features for the DM
- [ ] Start drafting the CDM
- [ ] Creating Definitions for relationships and the business objects

**Notes:**
- Jas and Adrian to work on the Subscription model of the diagram
- Payment Schema we need to examine everyone's style of Payment and incorporate the best elements together
- Due to missing members, reschedule the meeting to another day. 
- Comments on issues due by EOD 
    - ( Jas viewability issue with Github (comments not visible) ) Mods don't like Jas
- Oliver to upload DM

**Comment by ambergarcia** [comment]
https://github.com/G915-2-Data-Modeling-381/Project-1-eStreamingMovies/issues/12

**Comment by ambergarcia** [comment]
Not enough members to complete tasks, rescheduling meeting.
